### ISSUE TITLE
SmartQQ初始化失败: 请求失败，Api返回码[1202]

### ISSUE THREAD

**Issue by MarkHan1213** [Jamling/SmartQQ4IntelliJ#13]
扫码以后出现这个问题

**Comment by Jamling** [comment]
请在官网http://w.qq.com/登录，再退出。过个1分钟再扫码登录。

**Comment by MarkHan1213** [comment]
OK，我试试看

**Comment by MarkHan1213** [comment]
还是不行

**Comment by Jamling** [comment]
@MarkHan1213 你的账号在官网可以正常登录吗？

**Comment by MarkHan1213** [comment]
可以的，在那个官网的smartQQ上可以登录的

**Comment by Jamling** [comment]
@MarkHan1213 方便的话，把日志发给我，我看是哪个api 1202了。

**Comment by ice1000** [comment]
> SmartQQ初始化失败: 请求失败，Api返回码[1202]

同样的问题。这是 StackTrace :

```
SmartQQ初始化失败: 请求失败，Api返回码[1202]
cn.ieclipse.smartim.exception.LogicException: 请求失败，Api返回码[1202]
	at com.scienjus.smartqq.client.SmartQQApi.getResponseJson(SmartQQApi.java:589)
	at com.scienjus.smartqq.client.SmartQQApi.getJsonArrayResult(SmartQQApi.java:540)
	at com.scienjus.smartqq.client.SmartQQApi.getRecentList(SmartQQApi.java:430)
	at com.scienjus.smartqq.client.SmartQQClient.init(SmartQQClient.java:230)
	at cn.ieclipse.smartqq.QQContactView.doLoadContacts(QQContactView.java:94)
	at cn.ieclipse.smartim.views.IMContactView$2.run(IMContactView.java:63)
```

**Comment by Jamling** [comment]
@ice1000 是否重试也还是api返回1202？

**Comment by ice1000** [comment]
我还没有重试过，出现问题我就没用这个了。。。【
今晚再试试吧，到时候会答复 :wink:

**Comment by MarkHan1213** [comment]
SmartQQ初始化失败: 请求失败，Api返回码[1202]
cn.ieclipse.smartim.exception.LogicException: 请求失败，Api返回码[1202]
	at com.scienjus.smartqq.client.SmartQQApi.getResponseJson(SmartQQApi.java:589)
	at com.scienjus.smartqq.client.SmartQQApi.getJsonArrayResult(SmartQQApi.java:540)
	at com.scienjus.smartqq.client.SmartQQApi.getRecentList(SmartQQApi.java:430)
	at com.scienjus.smartqq.client.SmartQQClient.init(SmartQQClient.java:230)
	at cn.ieclipse.smartqq.QQContactView.doLoadContacts(QQContactView.java:94)
	at cn.ieclipse.smartim.views.IMContactView$2.run(IMContactView.java:63)

看来是一样的错，我AS 也是这个错，IDEA 也是这个错，然后去smartQQ上登录以后，退出，过一阵再用插件登录，还是报这个错，另外一个QQ号登录成功过一次

**Comment by Jamling** [comment]
@MarkHan1213 谢谢反馈，目前看来，这个1202还真是无解啊，跟某些账号相关，只能使用这些账号去官网登录抓包分析与java客户端抓包分析了。idea插件和eclipse插件使用的中间层(smartqq.jar)是一样子的。
