### ISSUE TITLE
QQ扫码报错了？

### ISSUE THREAD

**Issue by SbyXlmm** [Jamling/SmartQQ4IntelliJ#28]
```
SmartQQ初始化失败: 请求失败，Api返回码[1202]
cn.ieclipse.smartim.exception.LogicException: 请求失败，Api返回码[1202]
	at com.scienjus.smartqq.client.SmartQQApi.getResponseJson(SmartQQApi.java:589)
	at com.scienjus.smartqq.client.SmartQQApi.getJsonArrayResult(SmartQQApi.java:540)
	at com.scienjus.smartqq.client.SmartQQApi.getRecentList(SmartQQApi.java:430)
	at com.scienjus.smartqq.client.SmartQQClient.init(SmartQQClient.java:230)
	at cn.ieclipse.smartqq.QQContactView.doLoadContacts(QQContactView.java:94)
	at cn.ieclipse.smartim.views.IMContactView$2.run(IMContactView.java:63)
```

**Comment by Jamling** [comment]
1202目前无解，我这边一直也办法复现。好像跟某些账号有关，有些账号在获取最近联系人时，一直返回1202。考虑下个版本在返回1202时，返回一个空列表。

**Comment by Jamling** [comment]
v2.1.0版本中，请求失败，返回空列表
