### ISSUE TITLE
SmartQQ初始化失败: 请求失败，Api返回码[100003]

### ISSUE THREAD

**Issue by lwydyby** [Jamling/SmartQQ4IntelliJ#45]
SmartQQ初始化失败: 请求失败，Api返回码[100003]
cn.ieclipse.smartim.exception.LogicException: 请求失败，Api返回码[100003]
	at com.scienjus.smartqq.client.SmartQQApi.getResponseJson(SmartQQApi.java:592)
	at com.scienjus.smartqq.client.SmartQQApi.getJsonObjectResult(SmartQQApi.java:537)
	at com.scienjus.smartqq.client.SmartQQApi.getFriendListWithCategory(SmartQQApi.java:373)
	at com.scienjus.smartqq.client.SmartQQClient.init(SmartQQClient.java:222)
	at cn.ieclipse.smartqq.QQContactView.doLoadContacts(QQContactView.java:84)
	at cn.ieclipse.smartim.views.IMContactView$2.run(IMContactView.java:63)

**Comment by Jamling** [comment]
拉取好友异常了，点击X退出登录，再重新扫码试试。

**Comment by eatmoresushi** [comment]
同样问题，jetbrains版， SmartQQ初始化失败: 请求失败，Api返回码[100003]
点击X退出登录，再重新扫码试过多次还是不行

**Comment by Jamling** [comment]
在官网https://w.qq.com登录一次，然后再退出。再重试。

**Comment by eatmoresushi** [comment]
官网登进去也是没有好友 腾讯那边的问题吧

**Comment by Jamling** [comment]
是的，我表示，这个锅得由腾讯来背

**Comment by Jamling** [comment]
腾讯服务已恢复正常
