### ISSUE TITLE
java.util.ConcurrentModificationException occured!

### ISSUE THREAD

**Issue by shellcompute** [Jamling/SmartQQ4IntelliJ#47]
### Description
I've just talked with a friend for some words, and sent a picture with my mobile-qq, after that, I cleared the message-history in my idea, and then I got this error alert. It seems that you changed the arraylist object while iterate it.

### Error Detail:

```java
null
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:903)
	at java.util.ArrayList$Itr.next(ArrayList.java:853)
	at cn.ieclipse.wechat.WXContactTreeNode.update(WXContactTreeNode.java:38)
	at cn.ieclipse.wechat.WXContactView.doUpdateContacts(WXContactView.java:118)
	at cn.ieclipse.smartim.views.IMContactView$4.run(IMContactView.java:89)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Thanks!

**Comment by Jamling** [comment]
Thank you for your feedback~
