### ISSUE TITLE
SmartQQ初始化失败

### ISSUE THREAD

**Issue by xman55555** [Jamling/SmartQQ4IntelliJ#56]
SmartQQ初始化失败

cn.ieclipse.smartim.exception.LogicException: 请求失败，Api返回码[13]
	at com.scienjus.smartqq.client.SmartQQApi.getResponseJson(SmartQQApi.java:592)
	at com.scienjus.smartqq.client.SmartQQApi.getJsonObjectResult(SmartQQApi.java:537)
	at com.scienjus.smartqq.client.SmartQQApi.getGroupList(SmartQQApi.java:257)
	at com.scienjus.smartqq.client.SmartQQClient.init(SmartQQClient.java:226)
	at cn.ieclipse.smartqq.QQContactView.doLoadContacts(QQContactView.java:84)
	at cn.ieclipse.smartim.views.IMContactView$2.run(IMContactView.java:63)

**Comment by xman55555** [comment]
不知道什么原因,微信可以用,但是qq不行,貌似是qq的服务有问题?打开web2.qq.com,一下有一下没有的

**Comment by Jamling** [comment]
SmartQQ又不稳定了。待腾讯修复吧

**Comment by likexian123** [comment]
SmartQQ 现在已经停止使用了吧

**Comment by Jamling** [comment]
@likexian123 是滴
