### ISSUE TITLE
SmartQQ初始化失败: 请求失败，Api返回码[100100]

### ISSUE THREAD

**Issue by jakeyChen1994** [Jamling/SmartQQ4IntelliJ#59]
SmartQQ初始化失败: 请求失败，Api返回码[100100]
cn.ieclipse.smartim.exception.LogicException: 请求失败，Api返回码[100100]
	at com.scienjus.smartqq.client.SmartQQApi.getResponseJson(SmartQQApi.java:592)
	at com.scienjus.smartqq.client.SmartQQApi.getJsonObjectResult(SmartQQApi.java:537)
	at com.scienjus.smartqq.client.SmartQQApi.getFriendListWithCategory(SmartQQApi.java:373)
	at com.scienjus.smartqq.client.SmartQQClient.init(SmartQQClient.java:222)
	at cn.ieclipse.smartqq.QQContactView.doLoadContacts(QQContactView.java:84)
	at cn.ieclipse.smartim.views.IMContactView$2.run(IMContactView.java:63)

**Comment by Jamling** [comment]
感谢您的使用与支持，SmartQQ还有10天就停止服务了。这期间服务不稳定，腾讯应该也不会再维护了。
